taf2/curb

README.markdown

installation instructions for windows added to readme

---

README.markdown

This would be handy for those who are trying to gem install curb on centos or rhel.
ruby-devel is needed because curb compilation requires ruby.h

Added RedHat dependencies installation note

---

ext/curb_easy.c

Hi,
I encountered strange issue on OS X version `10.9.5` with Ruby version `2.1.3`, `2.2.0` and `2.2.1`
```ruby
> irb ./play.rb
play.rb(main):001:0> require 'curb'
=> true
play.rb(main):002:0> url = 'http://baidu.com'
=> "http://baidu.com"
play.rb(main):003:0> client = Curl::Easy.new
=> #<Curl::Easy>
play.rb(main):004:0> client.url = url
=> "http://baidu.com"
play.rb(main):005:0> client.http_get
Curl::Err::GotNothingError: Server returned nothing (no headers, no data)
from /Users/forresty/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/curb-0.8.7/lib/curl/easy.rb:72:in `perform'
from /Users/forresty/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/curb-0.8.7/lib/curl/easy.rb:294:in `http'
from /Users/forresty/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/curb-0.8.7/lib/curl/easy.rb:294:in …
```

Strange problem on OS X

---

ext/curb_easy.c
ext/curb_easy.h
tests/tc_curl_easy.rb
tests/timeout.rb

Resolves #162. Also includes a fix to make it possible to compile the gem with versions of libcurl < 7.40.0.

Add timeout_ms, connect_timeout_ms options

---

curb.gemspec

Remove defunct rubyforge_project setting from gemspec

---

lib/curl/easy.rb

fix issue #263 , #253 
doc in http://ruby-doc.org/core-2.2.0/Exception.html
[[ Programs may make subclasses of Exception, typically of StandardError or RuntimeError, to provide custom classes and add additional information. See the subclass list below for defaults for raise and rescue. ]]

fix Exception to StandardError

---

ext/curb_easy.c

When making a lot of curb requests, the connections seem to stay open for quite some time. Curb doesn't reuse these connections though. To prevent the open connections, one might want to set CURLOPT_FORBID_REUSE.

Allow setting of CURLOPT_FORBID_REUSE

---

ext/curb.c
ext/curb_easy.c
ext/extconf.rb

Adds support for:
* Curl::CURL_SSLVERSION_TLSv1_0
* Curl::CURL_SSLVERSION_TLSv1_1
* Curl::CURL_SSLVERSION_TLSv1_2
/ping https://github.com/taf2/curb/issues/258

Request specific TLS version with additional constants

---

README.markdown
Rakefile
bench/curb_multi.rb
ext/curb.c
ext/curb_multi.c
lib/curb.gemspec.erb
lib/curl/multi.rb

This patch adds support for a bunch of libcurl options for HTTP/2 support:
```ruby
Curl::CURL_HTTP_VERSION_2_0
Curl::HTTP_VERSION_2_0
Curl::CURLPIPE_NOTHING # same as pipeline=false before
Curl::CURLPIPE_HTTP1 # same as pipeline=true before
Curl::CURLPIPE_MULTIPLEX # HTTP/2 multiplexing
Curl::PIPE_NOTHING
Curl::PIPE_HTTP1
Curl::PIPE_MULTIPLEX
```
It _should_ maintain backwards compatibility with the old `pipeline` boolean values, as well as supporting the new multiplex option, and the corresponding ints that true/false represented, but I'm not that proficient at C, and have never hacked on a ruby gem before, so please do review carefully!

Add support for HTTP/2 and Multiplexing

---

ext/curb_multi.c

Different curl handles should use different keys in the requests hash.
For 64-bit platforms, a long value should be used as the key.
Note: For Windows, an additional bugfix may be necessary, because long is always a 32 bit type on Windows.

Save curl handles as long in the requests hash

---

ext/curb_easy.c

Curb did not allow negative values for http_auth_types, but the values for
CURLAUTH_ANY and CURLAUTH_ANYSAFE are negative.
This also fixes the bug that curb used :any instead of :anysafe.

Fix http_auth_types for :any and :anysafe

---

ext/curb.c
ext/curb_easy.c
ext/curb_macros.h
ext/curb_multi.c
ext/curb_upload.c

Some values of the 'long' type cannot be represented as a Fixnum, e.g. the curl constant `CURLAUTH_ANY` is a Bignum.
In order to support such values, `LONG2NUM` and `NUM2LONG` must be used.
`INT2FIX`, `FIX2INT`, `FIX2LONG` and `LONG2FIX` must not be used (except in some special cases), because the value may get truncated.
The performance impact of this change is very small and negligible.
Setting `http_auth_types = :any` now really works.

Use LONG2NUM and NUM2LONG to support all values of the 'long' type

---

lib/curl/easy.rb

The reason phrase may be empty, see RFC 7230 section 3.1.2

Support empty reason phrases in the HTTP status line

---

README.markdown

The curb modules are `Curl`, which makes it unclear to new ruby users as to what they should be requiring.
Opened this PR as I'm going through some ruby basics with someone and they were confused by the module naming schema vs. the gem name.

Add a require statement to help with new users who are getting started with curb

---

tests/helper.rb

On my Windows (10 x64-mingw) dev box, tests were failing because of a malformed URL. This tiny PR fixes that.

Make tests work on Windows

---

curb.gemspec

The Rubyforge URL redirects to this repo, so I updated the URL in the gemspec to point here directly.

Goodbye Rubyforge

---

ext/curb_easy.c
ext/curb_easy.h
tests/tc_curl_easy_resolve.rb

As discussed in #49, there currently is no way to set the CURLOPT_RESOLVE list. This is needed when SSL backend servers need to be accessed on a different IP address than listed in the DNS. One use case is for checking multiple SSL backend servers for consistency.
The pull request includes unit tests for the new setter and getter methods, and docstrings that hopefully clarify the usage.

Add Curl::Easy#resolve method to implement static IP overrides, bypassing DNS

---

lib/curl/easy.rb

While it violates the protocol for the status line not to be there, the current `NoMethodError` error that results is confusing.

Prevent `NoMethodError` when no HTTP Status

---

README.markdown
ext/curb.c
ext/extconf.rb

The `have_constant` method puts the whole constant name to upcase, but the various ssl versions constants aren't fully upcase, so they're never found.  This patch updates those constants to use a symbol with the right case.
This PR also updates the README to reflect the need to run `rake compile` before `rake install` to have the makefile generated.
Sadly, the PR also includes a few spacing changes I was too lazy to remove, tell me if this is a problem.
Cheers,
Lta.
Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>

extconf.rb: Fix SSL versions constant names

---

ChangeLog
lib/curl/easy.rb

The HTTP/2 RFC specifies the status header as HTTP/2 200 CRLF, it's not
mandatory to return the number as float, nor do they add the status info
anymore.
This PR fixes it so it is still able to work with HTTP/2

Support HTTP/2 status header

---

Gemfile.lock
curb.gemspec
tests/helper.rb

Travis runs `bundle install --deployment` and it fails because the
Gemfile.lock is not up to date.
`curb` version has been updated, but `bundle install` has not been
executed. Bundler is expected to fail with `--deployment` flag if
Gemfile.lock is not up to date.
This commit also removes deprecated fields from the gemspec file.

fix `bundle install --deployment`

---

lib/curl.rb
tests/tc_curl.rb

Given an URL without query params Curb would add `?` at the end. This
has been introduced in commit 32fa6d7.
This happens because we set `uri.query` to empty string and URI will
treat this as a valid query and it will add `?`. This does not happen
when the query is set to nil.
I have decide to early return if extra parameters are not passed. It
will work whatever there were query params in the original url or not
because we don't change `#query` and it's set correctly.
Added unit tests for all use cases.
The empty `?` is meangingless for the browser/server, but it can be
significant for caching strategies. I use `curb` to purge Varnish
cache for individual urls and addition of `?` breaks this because
the purged URL is different from what I expected.

do not append `?` to urls if there are no query parameters

---

README.markdown

There's small trouble I found while installing curb on Windows machine. Fix in readme allows to avoid it.

fix small readme mistake

---

ext/curb_errors.c

from CHANGES:
ssl: deprecate CURLE_SSL_CACERT in favour of a unified error code
Long live CURLE_PEER_FAILED_VERIFICATION

Fix build with curl 7.62.0

---

ext/curb_easy.c

curb checks for CURLOPT_RESOLVE properly but doesn't guard its usage everywhere.
This fixes building curb 0.9.x on CentOS 6 (with curl 7.19.x), which for us failed with the following:
```
current directory: /home/jokwan/.gem/ruby/2.3.0/gems/curb-0.9.6/ext
make "DESTDIR="
compiling curb.c
compiling curb_easy.c
curb_easy.c: In function ‘ruby_curl_easy_setup’:
curb_easy.c:2357: error: ‘CURLOPT_RESOLVE’ undeclared (first use in this function)
curb_easy.c:2357: error: (Each undeclared identifier is reported only once
curb_easy.c:2357: error: for each function it appears in.)
curb_easy.c:2357: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
make: *** [curb_easy.o] Error 1
make failed, exit code 2
```

guard use of CURLOPT_RESOLVE in #if HAVE_CURLOPT_RESOLVE

---

ext/curb_easy.c
tests/tc_curl_easy.rb

The setter used `CURB_IMMED_SETTER` macro and it casts value to `long`
and loses precision if float was passed. C will round down as part of
the conversion and if it converts to 0 then the IMMED_GETTER will return
nil.
This results in a confusing output described in #355.
This commit deperecates `CURLOPT_TIMEOUT` option and the code will rely
exclusively on `timeout_ms` (and `CURLOPT_TIMEOUT_MS` accordingly).
There are minor user-facing changes:
* timeout and timeout_ms will not return nil anymore
* change of timeout will now also change timeout_ms respectively
* timeout will return numeric rather than fixnum
Otherwise everything should be working as expected.

fix timeout and timeout_ms to handle floats and negative numbers

---

.travis.yml
Gemfile.ruby-1.8
Gemfile.ruby-1.8.lock
Rakefile
ext/curb_multi.c
tests/helper.rb
tests/tc_curl_easy.rb

Fixes #304 (details in commit messages)
It also enables builds against ruby 1.8 on Travis (new Gemfile with minimal gems and backports was required).
Ruby 1.8 is long dead, but the fix is simple and it will allow anyone still stuck on 1.8 to upgrade easier. With Travis configured the drop of support becomes an option rather than a fact ;)

fixes for ruby 1.8

---

.gitignore
Gemfile
Gemfile.lock
Gemfile.ruby-2.1
Gemfile.ruby-2.1.lock
Rakefile
tasks/docker.rake
tasks/rake_helpers.rb
tasks/utils.rb

This commit adds a set of rake tasks to enable use of docker for
development.
Task `rake docker:environment` makes necessary configuration and `rake
docker:test_all` will then run tests on all supported rubies.
Currently supported rubies are 2.0, 2.1, 2.2, 2.3, 2.4, 2.5.
There were significant changes in ruby 2.2 and many gems dropped
support for older versions so they can't be upgraded or are currently
broken.
Curb has minimal set of ruby dependencies and this isn't too much
of an issue for the gem itself, but it holds us back when it comes to
the build system maintenance.
Maintaining backward compatibility requires either a lot of patience to
wait and debug error messages reported by Travis or complex local setup.
Introduction of docker aims to solve this problem by providing
convenient …

enable builds in docker

---

ext/curb_easy.c
tests/tc_curl_maxfilesize.rb

This lets the caller set the CURLOPT_MAXFILESIZE curl option.

CURLOPT_MAXFILESIZE option

---

curb.gemspec

The license outlined in LICENSE is the Ruby license, whereas the license given in the gemspec was MIT.

Fix discrepancy between gemspec and LICENSE

---

.travis.yml
tasks/rake_helpers.rb

Ruby 2.6.0 has been traditionally released on Christmas.

support ruby 2.6

---

ChangeLog.md
ext/curb.h
ext/curb_multi.c
lib/curl/multi.rb
tests/tc_curl_multi.rb

Add ```Curl::Multi.autoclose``` and ```Curl::Multi#close``` to address connection leaks related to waiting for GC to run to clean up Multi handles.  If you're using Curl.get/Curl.post and generally fetching the same hosts say for an internal service etc... using the default of autoclose = false, is probably ideal because you'll keep connections alive for commonly accessed services.  If however you're making a lot of requests to many different external services you may want to run with autoclose=true.   In general, you should test which works best for your application e.g. running something like:
```netstat -anp  | grep WAIT``` on your server and ensure that it isn't growing out of control.

Autoclose close

---

curb.gemspec
lib/curb.gemspec.erb

Updating this URL so that the link on rubygems will no longer be a dead link after the next version of this gem is cut.

Update homepage in gemspec [ci skip]

---

ext/curb_easy.c

The following code does not have the intended behavior
curl.setopt(Curl::CURLOPT_HAPROXYPROTOCOL, 1)
The expected header does not get set. This looks like a small typo.
Instead of passing the truthy HAVE_CURLOPT_HAPROXYPROTOCOL we should
be passing CURLOPT_HAPROXYPROTOCOL to curl_easy_setopt.
Validated by rebuilding the gem with the changes and re-testing.

fix enabling haproxy protocol

---

ext/curb_easy.c

Add Curl::CURLOPT_SSL_SESSIONID_CACHE constant support into setopt method. [See more about this parameter](https://curl.se/libcurl/c/CURLOPT_SSL_SESSIONID_CACHE.html)

Add CURLOPT_SSL_SESSIONID_CACHE option into setopt

---

ext/curb_easy.c

There is a small typo in ext/curb_easy.c.
Should read `pipelining` rather than `pippelining`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, pippelining -> pipelining

---

Gemfile.lock

This PR is an attempt to avoid the following build error in: https://travis-ci.org/github/taf2/curb/jobs/741142541
```
$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
The gemspecs for path gems changed
```
It avoids the error  and continues!
This takes us to the _next build error_ - which is a good thing.
https://github.com/taf2/curb/compare/fa6e08ecb878...fc43c798332b introduced a .11 but the Gemfile.lock wasn't informed.

Build fix: Gemfile.lock: update gems to avoid changes in lockfile

---

ext/extconf.rb

Remove double quotes when returned by "curl-config --ca"
As discussed into https://github.com/taf2/curb/issues/452

Avoid double quotes into CURL_CONFIG_CA filename

---

ext/curb_easy.c

unify condition check for remaining vs read_bytes and remove unneeded branch, and fix return value as the result.
Fixes #451 .

FIX: for callback function read_data_handler

---

lib/curl/multi.rb

`Curl::Multi.http` doesn't currently support setting `:on_missing` callbacks in options provided with urls_with_config.

Add :on_missing to callbacks supported by Curl::Multi.http

---

tests/tc_curl_easy.rb

This test covers http verb conversion to string, which is not specifically related to any service.
This also include fix of broken link.

Use `TestServlet.url` instead of external connectivity

---

lib/curb.gemspec.erb

The project is has Ruby license, however, the MIT keeps popping up due to this template. So fix the license in template to fix it once and for all.
This should help to address #436, which seems to be the most recent reincarnation of the issue

Use `Ruby` license in curb.gemspec.erb

---

curb.gemspec
ext/curb_easy.c
tests/helper.rb
tests/tc_curl_easy_cookielist.rb

Add interface to call `curl_easy_setopt` - [`Easy::setopt`](https://www.rubydoc.info/github/taf2/curb/Curl/Easy#setopt-instance_method) - with `CURLOPT_COOKIELIST`.
It's not something like `#cookielist=`, because I believe this method should be more Rubyish, like add constants for [special values](https://curl.se/libcurl/c/CURLOPT_COOKIELIST.html#ALL), support array argument, or even use `CURB_OBJECT_HSETTER` instead of simply passing it to libcurl and keep it consistent with other options (like you do this with `headers=`/`CURLOPT_HTTPHEADER`, for example, and set `enable_cookies` flag accordingly). All of this requires much more effort, and I'm happy with this simple raw interface.

Add `CURLOPT_COOKIELIST` support

---

ext/curb_multi.c
ext/extconf.rb
tests/tc_curl_multi.rb

https://curl.se/libcurl/c/CURLMOPT_MAX_HOST_CONNECTIONS.html

allow configuration curl multi MAX_HOST_CONNECTIONS
